export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const DISPLAY_NOTIFICATION_DRAWER = "DISPLAY NOTIFICATION DRAWER";
export const HIDE_NOTIFICATION_DRAWER = "HIDE NOTIFCATION DRAWER";
